### ISSUE TITLE
Cannot run-client

### ISSUE THREAD

**Issue by zicmama** [michaelcunningham19/video-speech-recognition#7]
Followed readme, but I got this errors

/run-client.sh
```
./run-client.sh: ligne 2: http-server : commande introuvable
```

./run-server.sh 
```
rm: impossible de supprimer './bin/vsr_x64': Aucun fichier ou dossier de ce type
main.go:12:2: cannot find package "server/encoder" in any of:
	/usr/lib/go-1.10/src/server/encoder (from $GOROOT)
	/home/fred/go/src/server/encoder (from $GOPATH)
main.go:13:2: cannot find package "server/transcriber" in any of:
	/usr/lib/go-1.10/src/server/transcriber (from $GOROOT)
	/home/fred/go/src/server/transcriber (from $GOPATH)
./run-server.sh: ligne 9: ../../bin/vsr_x64: Aucun fichier ou dossier de ce type
```

**Comment by michaelcunningham19** [comment]
Hi @zicmama 

You'll need to install `http-server` through `brew` - I realized this was not explained in the README and have switched this to using the node implementation, using `npx`. Now, as of https://github.com/michaelcunningham19/video-speech-recognition/commit/22b6bef396793e5dd4a4f8894e0408afd8034ff7 you can use these new commands to start the client and server.

Regarding the Go error you are seeing, that is due to using an old version. Go modules were introduced in 1.11, and the latest version is 1.15.6 at the time of writing.
